language: minimal
os: linux
dist: focal

install:
- . /etc/os-release && echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - && sudo apt-get update -y && sudo apt-get install -y podman fuse-overlayfs uidmap slirp4netns

stages:
- build-and-test

matrix:
  include:
    - stage: build-and-test
      env: fedora=rawhide
    - stage: build-and-test
      env: fedora=latest
    - stage: build-and-test
      env: centos=8
    - stage: build-and-test
      env: centos=centos7
    - stage: build-and-test
      env: centos=centos6

before_script:
- if test -n "$fedora" ; then sed -i "s#^FROM.*#FROM registry.fedoraproject.org/fedora:$fedora#" tests/Dockerfile ; fi
- if test -n "$centos" ; then sed -i "s#^FROM.*#FROM centos:$centos#" tests/Dockerfile ; fi

script:
- podman build -t mod_authnz_pam -f tests/Dockerfile .
- podman run --name mod_authnz_pam --rm -d mod_authnz_pam
- podman exec mod_authnz_pam tests/run.sh
